name: flutter_less
description: A dart package that helps implement the BLoC pattern.
version: 0.0.6
homepage: https://github.com/vodino/flutter_less.git

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
